version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - barrel-app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - barrel-app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: barrel_app
      MYSQL_USER: barrel_user
      MYSQL_PASSWORD: barrel_password
    networks:
      - barrel-app

networks:
  barrel-app:
