version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      - barrel-app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - barrel-app


  mysql:
    image: 'mysql:8.0'
    environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=barrel_app
        - MYSQL_USER=barrel_user
        - MYSQL_PASSWORD=barrel_password
    ports:
        - '5002:3306'
    networks:
      - barrel-app

networks:
  barrel-app:
